# Generated by Django 5.0.8 on 2024-08-08 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pre_matches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookmaker', models.CharField(max_length=500)),
                ('teams', models.CharField(max_length=500)),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=500)),
                ('region', models.CharField(max_length=500)),
                ('sport', models.TextField(max_length=500)),
                ('odds', models.IntegerField()),
            ],
        ),
    ]
