# Generated by Django 5.0.8 on 2024-08-08 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MartonApp', '0003_alter_pre_matches_odds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pre_matches',
            name='odds',
            field=models.FloatField(),
        ),
    ]
