# Generated by Django 5.0.8 on 2024-08-08 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MartonApp', '0006_alter_pre_matches_odds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pre_matches',
            name='odds',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
    ]
