# Generated by Django 5.0.8 on 2024-08-20 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MartonApp', '0007_alter_pre_matches_odds'),
    ]

    operations = [
        migrations.CreateModel(
            name='live_matches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookmaker', models.CharField(max_length=500)),
                ('teams', models.CharField(max_length=500)),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=500)),
                ('region', models.CharField(max_length=500)),
                ('sport', models.TextField(max_length=500)),
                ('odds', models.DecimalField(decimal_places=5, max_digits=10)),
            ],
        ),
    ]
